import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Footer from "./Footer";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  withNavBar = true,
  withFooter = true,
}: Readonly<{
  children: React.ReactNode;
  withNavBar?: boolean;
  withFooter?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {withNavBar && <NavBar />}
        {children}
        {withFooter && <Footer />}
      </body>
    </html>
  );
}

