import "./globals.css";
import NavBar from "./NavBar";
import Footer from "./Footer";
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Care connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

